language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
env:
  - COMPOSER_PROCESS_TIMEOUT=4800
install:
  - travis_retry composer install --no-interaction
script:
  - composer cs
  - composer test -- --coverage-clover clover.xml
after_success:
  - travis_retry php vendor/bin/php-coveralls -v --coverage_clover clover.xml --json_path coveralls-upload.json

